package oruk;


import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import oru.inf.InfException;

public class ForskningUtbildningAnslag extends javax.swing.JPanel {

    private static OrukDB db;
    private static ArrayList<String> enLista;
    private static String titel;

    

    /**
     * Creates new form ForskningUtbildning
     * @param db
     */
    public ForskningUtbildningAnslag(OrukDB db) {
        initComponents();
        this.db=db;
        enLista = new ArrayList<>(); 
        fyllLista();
        kollaAdmin();
    }
    
    public void kollaAdmin() {
        try {
            String anvandare = Huvudfonster.getAnvandarnamn();
            btnAndra.setVisible(false);
            btnTaBort.setVisible(false);

            String data = "SELECT GRAD FROM ANVANDARE WHERE MAILADRESS='" + anvandare + "'";
            String data1 = db.fetchSingle(data);
            
            if(data1.equals("S") || data1.equals("A"))
            {
                btnAndra.setVisible(true);
                btnTaBort.setVisible(true);
                
            
            }
        
        } 
        catch (InfException ex) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelForskning = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnSe = new javax.swing.JButton();
        btnAndra = new javax.swing.JButton();
        btnTaBort = new javax.swing.JButton();

        panelForskning.setBackground(new java.awt.Color(255, 255, 255));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        btnSe.setText("Se projekt");
        btnSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeActionPerformed(evt);
            }
        });

        btnAndra.setText("Ändra inlägg");
        btnAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraActionPerformed(evt);
            }
        });

        btnTaBort.setText("Ta bort inlägg");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelForskningLayout = new javax.swing.GroupLayout(panelForskning);
        panelForskning.setLayout(panelForskningLayout);
        panelForskningLayout.setHorizontalGroup(
            panelForskningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelForskningLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelForskningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelForskningLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnSe))
                    .addGroup(panelForskningLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTaBort))
                    .addGroup(panelForskningLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAndra)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panelForskningLayout.setVerticalGroup(
            panelForskningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelForskningLayout.createSequentialGroup()
                .addGroup(panelForskningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelForskningLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnSe)
                        .addGap(30, 30, 30)
                        .addComponent(btnAndra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTaBort))
                    .addGroup(panelForskningLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelForskning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelForskning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeActionPerformed
        new Forsk(db, titel).setVisible(true);     
    }//GEN-LAST:event_btnSeActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        titel = jList1.getSelectedValue();
          
    }//GEN-LAST:event_jList1MouseClicked

    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed
        new AdminAndraInlagg2(db, titel).setVisible(true);
    }//GEN-LAST:event_btnAndraActionPerformed

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Vill du ta bort inlägget?", "Ta bort inlägg",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
     if (response == JOptionPane.NO_OPTION) {

    } else if (response == JOptionPane.YES_OPTION) {
            try {
                String data1 = "DELETE FROM GORA_INLAGG WHERE IID=(SELECT IID FROM INLAGG WHERE RUBRIK='" + titel + "')";
                String data2 = "DELETE FROM KOMMENTERA_INLAGG WHERE IID=(SELECT IID FROM INLAGG WHERE RUBRIK='" + titel + "')";
                String data3 = "DELETE FROM INLAGG WHERE IID=(SELECT IID FROM INLAGG WHERE RUBRIK='" + titel + "')";
                db.delete(data1);
                db.delete(data2);
                db.delete(data3);
                
                JOptionPane.showMessageDialog(null, "Inlägget har tagits bort");
                fyllLista();
                
                
            } catch (InfException ex) {
                
            }
        
      }
    }//GEN-LAST:event_btnTaBortActionPerformed
    
    public static void fyllLista() {
        DefaultListModel model = new DefaultListModel();
        try {
            enLista = db.fetchColumn("SELECT RUBRIK FROM INLAGG WHERE KATEGORI='1' OR KATEGORI='2'");
            String svar = "";
            for (int i = 0; i < enLista.size(); i++) {
                svar = enLista.get(i);
                model.addElement(svar);
            }
            
            jList1.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndra;
    private javax.swing.JButton btnSe;
    private javax.swing.JButton btnTaBort;
    private static javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelForskning;
    // End of variables declaration//GEN-END:variables
}
