/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oruk;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfException;

/**
 *
 * @author christianrudolphi
 */
public class Kommentar extends javax.swing.JFrame {

    private static OrukDB db;
    private static ArrayList<HashMap<String, String>> enLista;
    private static String inlaggsID;

    /**
     * Creates new form Kommentar
     */
    public Kommentar(OrukDB db, String inlaggsID) {
        initComponents();
        this.db = db;
        this.inlaggsID = inlaggsID;
        kollaAdmin();
        enLista = new ArrayList<>();
        fyllLista();

    }
    
    public void kollaAdmin() {
        try {
            String anvandare = Huvudfonster.getAnvandarnamn();
            btnTaBortKommentarer.setVisible(false);
            lblKommentarer.setVisible(false);
            
            

            String data = "SELECT GRAD FROM ANVANDARE WHERE MAILADRESS='" + anvandare + "'";
            String data1 = db.fetchSingle(data);
            
            if(data1.equals("S") || data1.equals("A"))
            {
                btnTaBortKommentarer.setVisible(true);
                lblKommentarer.setVisible(true);
                
                
            
            }
        
        } 
        catch (InfException ex) {

        }

    }

    public static void fyllLista() {

        try {

            enLista = db.fetchRows("SELECT KOMMENTAR, FORNAMN FROM KOMMENTERA_INLAGG JOIN ANVANDARE ON ANVANDARE.AID = KOMMENTERA_INLAGG.AID JOIN INLAGG ON KOMMENTERA_INLAGG.IID = INLAGG.IID WHERE KOMMENTERA_INLAGG.IID='" + inlaggsID + "'");
            
            if (enLista == null) {
                txtKommentar.setText("Inlägget har inga kommentarer");

            } else {

                String svar = "";

                for (int i = 0; i < enLista.size(); i++) {
                    svar += enLista.get(i).get("FORNAMN") + ": " + enLista.get(i).get("KOMMENTAR") + "\n\n";
                }

                txtKommentar.setText(svar);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPublicera = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInlagg = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtKommentar = new javax.swing.JTextArea();
        btnTaBortKommentarer = new javax.swing.JButton();
        lblKommentarer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnPublicera.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPublicera.setText("Kommentera");
        btnPublicera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPubliceraMouseClicked(evt);
            }
        });
        btnPublicera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPubliceraActionPerformed(evt);
            }
        });

        txtInlagg.setLineWrap(true);
        txtInlagg.setWrapStyleWord(true);
        txtInlagg.setColumns(20);
        txtInlagg.setRows(5);
        txtInlagg.setText("\n");
        jScrollPane2.setViewportView(txtInlagg);

        txtKommentar.setLineWrap(true);
        txtKommentar.setWrapStyleWord(true);
        txtKommentar.setEditable(false);
        txtKommentar.setColumns(20);
        txtKommentar.setRows(5);
        jScrollPane3.setViewportView(txtKommentar);

        btnTaBortKommentarer.setBackground(new java.awt.Color(0, 0, 0));
        btnTaBortKommentarer.setForeground(new java.awt.Color(0, 0, 0));
        btnTaBortKommentarer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortKommentarerActionPerformed(evt);
            }
        });

        lblKommentarer.setForeground(new java.awt.Color(0, 0, 0));
        lblKommentarer.setText("Ta bort kommentarer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTaBortKommentarer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(btnPublicera, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblKommentarer)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnTaBortKommentarer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPublicera)
                    .addComponent(lblKommentarer))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPubliceraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPubliceraMouseClicked
        fyllLista();
        txtInlagg.setText(null);
        txtInlagg.requestFocus();


    }//GEN-LAST:event_btnPubliceraMouseClicked

    private void btnPubliceraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPubliceraActionPerformed
        try {
            String anvandare = Huvudfonster.getAnvandarnamn();
            String aid = "SELECT AID FROM ANVANDARE WHERE MAILADRESS='" + anvandare + "'";
            String aid1 = db.fetchSingle(aid);
            String text = txtInlagg.getText();
            String id1 = db.getAutoIncrement("KOMMENTERA_INLAGG", "KIID");
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
            LocalDateTime now = LocalDateTime.now();
            String date = now.toString().substring(0, 10);
            String time = now.toString().substring(11, 19);

            String enStrang = "INSERT INTO KOMMENTERA_INLAGG VALUES(" + id1 + ", '" + text + "', '" + date + "', '" + time + "', " + aid1 + ", " + inlaggsID + ")";
            db.insert(enStrang);

        } catch (InfException ex) {

        }
    }//GEN-LAST:event_btnPubliceraActionPerformed

    private void btnTaBortKommentarerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortKommentarerActionPerformed
       new AdminTaBortKommentar(db, inlaggsID).setVisible(true);        
    }//GEN-LAST:event_btnTaBortKommentarerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPublicera;
    private javax.swing.JButton btnTaBortKommentarer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblKommentarer;
    private javax.swing.JTextArea txtInlagg;
    private static javax.swing.JTextArea txtKommentar;
    // End of variables declaration//GEN-END:variables
}
