/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oruk;

import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author carlf
 */
public class TaggaTagg extends javax.swing.JFrame {

    /**
     * Creates new form taggaAnvandare
     */
    public TaggaTagg(OrukDB db, String iid) throws InfException {
        initComponents();
        this.db = db;
        this.iid = iid;
        ComboBoxAutoComplete.enable(cmbxTaggar);
        getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        fyllCmbxTaggar();
        String anvandare = Huvudfonster.getAnvandarnamn(); 
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("icons\\oruklogoliten.png"));
        String aid = db.fetchSingle("SELECT AID FROM ANVANDARE WHERE MAILADRESS='" + anvandare + "'");       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        btnKlar = new javax.swing.JButton();
        btnLaggTill = new javax.swing.JButton();
        cmbxTaggar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btnKlar.setText("Klar");
        btnKlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlarActionPerformed(evt);
            }
        });

        btnLaggTill.setText("Lägg till");
        btnLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillActionPerformed(evt);
            }
        });

        cmbxTaggar.setEditable(true);
        cmbxTaggar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxTaggarActionPerformed(evt);
            }
        });

        jLabel1.setText("Lägg till tagggar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKlar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbxTaggar, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbxTaggar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLaggTill)
                    .addComponent(btnKlar))
                .addGap(114, 114, 114))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlarActionPerformed
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Inlägget har publicerats");
    }//GEN-LAST:event_btnKlarActionPerformed

    private void cmbxTaggarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxTaggarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxTaggarActionPerformed

    private void btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillActionPerformed
        try {
            String taggen = cmbxTaggar.getSelectedItem().toString();
            String tid = db.fetchSingle("SELECT TID FROM TAGG WHERE NAMN='" + taggen + "'");
            db.insert("INSERT INTO INLAGG_TAGG VALUES(" + iid + ", '" + tid + "')");
            JOptionPane.showMessageDialog(null, taggen + " har lagts till i inlägget");
        } catch (InfException ex) {
            Logger.getLogger(TaggaTagg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnLaggTillActionPerformed

 //Metod som körs i konstruktorn för att fylla JComboBoxen med användarnamn
    private void fyllCmbxTaggar() {
        try {
            ArrayList listan = new ArrayList();
            listan = db.fetchColumn("SELECT NAMN FROM TAGG");
            ArrayList<String> allaTaggar = new ArrayList<>();
            
            for (Object mailadress : listan) {
                String anvandare = mailadress.toString();
                allaTaggar.add(anvandare);
            }
            allaTaggar.sort(String::compareToIgnoreCase);
            
            for (String namn : allaTaggar) {
                cmbxTaggar.addItem(namn);
            }
            cmbxTaggar.setSelectedIndex(-1);
            
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());           
        }
    }

    private OrukDB db;
    private String iid;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKlar;
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JComboBox<String> cmbxTaggar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
